name = "node"
title = "Node.js"

toc_landing_pages = ["/fundamentals/authentication", "/fundamentals", "/fundamentals/crud", "/usage-examples"]

intersphinx = [
  "https://docs.mongodb.com/manual/objects.inv",
  "https://docs.atlas.mongodb.com/objects.inv",
]

[constants]
version = 4.1
package-name-org = "mongodb-org"
pgp-version = "{+version+}"
api = "https://mongodb.github.io/node-mongodb-native/{+version+}"
mongosh = "``mongosh``"
